version: "3.3"
services:
  nlp_api:
    container_name: "nlp_api"
    build:
      context: nlp-api
    ports:
      - "5003:5003"
    networks:
      network1:
        ipv4_address: 172.19.0.2

networks:
  network1:
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
